apiVersion: apps/v1
kind: Deployment
metadata:
  name: scan-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scan
  template:
    metadata:
      labels:
        app: scan
    spec:
      containers:
      - name: scan
        image: gcr.io/Azelyony/scan:v1.0.0
        env:
        - name: TELE_TOKEN
          valueFrom:
            secretKeyRef:
              name: scan-secret
              key: TELE_TOKEN
      imagePullSecrets:
      - name: gcr-secret
