apiVersion: apps/v1
kind: Deployment
metadata:
  name: scan-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scan
  template:
    metadata:
      labels:
        app: scan
    spec:
      containers:
      - name: scan
        image: gcr.io/Azelyony/scan:v1.0.0
        ports:
        - containerPort: 80
        volumeMounts:
        - name: data-volume
          mountPath: /data
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 80
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
      volumes:
      - name: data-volume
        emptyDir: {}
