apiVersion: batch/v1
kind: Job
metadata:
  name: my-job
spec:
  template:
    spec:
      containers:
      - name: my-job-container
        image: your-image:tag  # Replace with your image and tag
        command: ["your", "command"]  # Replace with your command
      restartPolicy: Never